/*
 * DO NOT EDIT THIS FILE BY HAND!  It is generated by MKfallback.sh.
 */

#include <curses.priv.h>
#include <term.h>

const TERMTYPE *_nc_fallback(const char *name GCC_UNUSED)
{
	/* the fallback list is empty */
	return((TERMTYPE *)0);
}
