#include "kdumper.h"

// The avail_writer.gh include file is automatically generated by the
// makefiles and contains a list of all available writers (identified
// by a source filename starting with "write_").

#undef WRITER
#define WRITER(w)	extern void	write_##w(void *, unsigned);
#include "avail_writers.gh"

#undef WRITER
#define WRITER(w)	{#w, write_##w},

struct writer available_writers[] = {
#include "avail_writers.gh"	
	{NULL, 0}
};
