/*
 * $QNXLicenseC:
 * Copyright 2007, QNX Software Systems. All Rights Reserved.
 * 
 * You must obtain a written license from and pay applicable license fees to QNX 
 * Software Systems before you may reproduce, modify or distribute this software, 
 * or any work that includes all or part of this software.   Free development 
 * licenses are available for evaluation and non-commercial purposes.  For more 
 * information visit http://licensing.qnx.com or email licensing@qnx.com.
 *  
 * This file may contain contributions from others.  Please review this entire 
 * file for other proprietary rights or license notices, as well as the QNX 
 * Development Suite License Guide at http://licensing.qnx.com/license-guide/ 
 * for other information.
 * $
 */





static const char unknown[] = "Unknown error";

const char * const sys_errlist[] = {
    /* 000 EOK			*/	"No error",
    /* 001 EPERM		*/	"Operation not permitted",
    /* 002 ENOENT		*/	"No such file or directory",
    /* 003 ESRCH		*/	"No such process",
    /* 004 EINTR		*/	"Interrupted function call",
    /* 005 EIO			*/	"Input/output error",
    /* 006 ENXIO		*/	"No such device or address",
    /* 007 E2BIG		*/	"Arg list too long",
    /* 008 ENOEXEC		*/	"Exec format error",
    /* 009 EBADF		*/	"Bad file descriptor",
    /* 010 ECHILD		*/	"No child processes",
    /* 011 EAGAIN		*/	"Resource temporarily unavailable",
    /* 012 ENOMEM		*/	"Not enough memory",
    /* 013 EACCES		*/	"Permission denied",
    /* 014 EFAULT		*/	"Bad address",
    /* 015 ENOTBLK		*/	"Block device required",
    /* 016 EBUSY		*/	"Resource busy",
    /* 017 EEXIST		*/	"File exists",
    /* 018 EXDEV		*/	"Improper link",
    /* 019 ENODEV		*/	"No such device",
    /* 020 ENOTDIR		*/	"Not a directory",
    /* 021 EISDIR		*/	"Is a directory",
    /* 022 EINVAL		*/	"Invalid argument",
    /* 023 ENFILE		*/	"Too many open files in system",
    /* 024 EMFILE		*/	"Too many open files",
    /* 025 ENOTTY		*/	"Inappropriate I/O control operation",
    /* 026 ETXTBSY		*/	"Text file busy",
    /* 027 EFBIG		*/	"File too large",
    /* 028 ENOSPC		*/	"No space left on device",
    /* 029 ESPIPE		*/	"Invalid seek",
    /* 030 EROFS		*/	"Read-only file system",
    /* 031 EMLINK		*/	"Too many links",
    /* 032 EPIPE		*/	"Broken pipe",
    /* 033 EDOM			*/	"Domain error",
    /* 034 ERANGE		*/	"Result too large",
    /* 035 ENOMSG		*/	"No message of desired type",
    /* 036 EIDRM		*/	"Identifier removed",
    /* 037 ECHRNG		*/	"Channel number out of range",
    /* 038 EL2NSYNC		*/	"Level 2 not synchronized",
    /* 039 EL3HLT		*/	"Level 3 halted",
    /* 040 EL3RST		*/	"Level 3 reset",
    /* 041 ELNRNG		*/	"Link number out of range",
    /* 042 EUNATCH		*/	"Protocol driver not attached",
    /* 043 ENOCSI		*/	"No CSI structure available",
    /* 044 EL2HLT		*/	"Level 2 halted",
    /* 045 EDEADLK		*/	"Resource deadlock avoided",
    /* 046 ENOLCK		*/	"No locks available",
    /* 047 ECANCELED	*/	"Operation canceled",
    /* 048 ENOTSUP		*/	"Not supported",
    /* 049 EDQUOT		*/	"Disc quota exceded",
    /* 050 EBADE		*/	"Invalid exchange",
    /* 051 EBADR		*/	"Invalid request descriptor",
    /* 052 EXFULL		*/	"Exchange full",
    /* 053 ENOANO		*/	"No anode",
    /* 054 EBADRQC		*/	"Invalid request code",
    /* 055 EBADSLT		*/	"Invalid slot",
    /* 056 EDEADLOCK	*/	"File locking deadlock",
    /* 057 EBFONT		*/	"Bad font file format",
    /* 058 EOWNERDEAD	*/	"Owner died holding lock",
    /* 059 ???			*/	unknown,
    /* 060 ENOSTR		*/	"Device not a stream",
    /* 061 ENODATA		*/	"No data (for no delay io)",
    /* 062 ETIME		*/	"Timer expired",
    /* 063 ENOSR		*/	"Out of streams resources",
    /* 064 ENONET		*/	"Machine is not on network",
    /* 065 ENOPKG		*/	"Package not installed",
    /* 066 EREMOTE		*/	"Too many levels of remote path",
    /* 067 ENOLINK		*/	"The link has been severed",
    /* 068 EADV		*/	"Advertise error",
    /* 069 ESRMNT		*/	"Srmount error",
    /* 070 ECOMM		*/	"Communication error on send",
    /* 071 EPROTO		*/	"Protocol error",
    /* 072 ???			*/	unknown,
    /* 073 ???			*/	unknown,
    /* 074 EMULTIHOP		*/	"multihop attempted",
    /* 075 ???			*/	unknown,
    /* 076 ???			*/	unknown,
    /* 077 EBADMSG		*/	"Bad message",
    /* 078 ENAMETOOLONG	*/	"Filename too long",
    /* 079 EOVERFLOW	*/	"Value too large to be stored in datatype",
    /* 080 ENOTUNIQ		*/	"Given name not unique",
    /* 081 EBADFD		*/	"FD invalid for this operation",
    /* 082 EREMCHG		*/	"Remote address changed",
    /* 083 ELIBACC		*/	"Can't access shared library",
    /* 084 ELIBBAD		*/	"Accessing a corrupted shared lib",
    /* 085 ELIBSCN		*/	".lib section in a.out corrupted",
    /* 086 ELIBMAX		*/	"Attempting to link in too many libs",
    /* 087 ELIBEXEC		*/	"Attempting to exec a shared lib",
    /* 088 EILSEQ		*/	"Illegal byte sequence.",
    /* 089 ENOSYS		*/	"Function not implemented",
    /* 090 ELOOP		*/	"Too many levels of symbolic links or prefixes",
    /* 091 ERESTART		*/	"Restartable system call",
    /* 092 ESTRPIPE		*/	"if pipe/FIFO, don't sleep in stream head",
    /* 093 ENOTEMPTY	*/	"Directory not empty",
    /* 094 EUSERS		*/	"Too many users (for UFS)",
    /* 095 ???			*/	unknown,
    /* 096 ???			*/	unknown,
    /* 097 ???			*/	unknown,
    /* 098 ???			*/	unknown,
    /* 099 ???			*/	unknown,
    /* 100 ???			*/	unknown,
    /* 101 ???			*/	unknown,
    /* 102 ???			*/	unknown,
    /* 103 EOPNOTSUPP	*/	"Operation not supported",
    /* 104 ???			*/	unknown,
    /* 105 ???			*/	unknown,
    /* 106 ???			*/	unknown,
    /* 107 ???			*/	unknown,
    /* 108 ???			*/	unknown,
    /* 109 ???			*/	unknown,
    /* 110 ???			*/	unknown,
    /* 111 ???			*/	unknown,
    /* 112 ???			*/	unknown,
    /* 113 ???			*/	unknown,
    /* 114 ???			*/	unknown,
    /* 115 ???			*/	unknown,
    /* 116 ???			*/	unknown,
    /* 117 ???			*/	unknown,
    /* 118 ???			*/	unknown,
    /* 119 ???			*/	unknown,
    /* 120 ???			*/	unknown,
    /* 121 ???			*/	unknown,
    /* 122 ESTALE		*/	"Potentially recoverable i/o error",
    /* 123 ???			*/	unknown,
    /* 124 ???			*/	unknown,
    /* 125 ???			*/	unknown,
    /* 126 ???			*/	unknown,
    /* 127 ???			*/	unknown,
    /* 128 ???			*/	unknown,
    /* 129 ???			*/	unknown,
    /* 130 ???			*/	unknown,
    /* 131 ???			*/	unknown,
    /* 132 ???			*/	unknown,
    /* 133 ???			*/	unknown,
    /* 134 ???			*/	unknown,
    /* 135 ???			*/	unknown,
    /* 136 ???			*/	unknown,
    /* 137 ???			*/	unknown,
    /* 138 ???			*/	unknown,
    /* 139 ???			*/	unknown,
    /* 140 ???			*/	unknown,
    /* 141 ???			*/	unknown,
    /* 142 ???			*/	unknown,
    /* 143 ???			*/	unknown,
    /* 144 ???			*/	unknown,
    /* 145 ???			*/	unknown,
    /* 146 ???			*/	unknown,
    /* 147 ???			*/	unknown,
    /* 148 ???			*/	unknown,
    /* 149 ???			*/	unknown,
    /* 150 ???			*/	unknown,
    /* 151 ???			*/	unknown,
    /* 152 ???			*/	unknown,
    /* 153 ???			*/	unknown,
    /* 154 ???			*/	unknown,
    /* 155 ???			*/	unknown,
    /* 156 ???			*/	unknown,
    /* 157 ???			*/	unknown,
    /* 158 ???			*/	unknown,
    /* 159 ???			*/	unknown,
    /* 160 ???			*/	unknown,
    /* 161 ???			*/	unknown,
    /* 162 ???			*/	unknown,
    /* 163 ???			*/	unknown,
    /* 164 ???			*/	unknown,
    /* 165 ???			*/	unknown,
    /* 166 ???			*/	unknown,
    /* 167 ???			*/	unknown,
    /* 168 ???			*/	unknown,
    /* 169 ???			*/	unknown,
    /* 170 ???			*/	unknown,
    /* 171 ???			*/	unknown,
    /* 172 ???			*/	unknown,
    /* 173 ???			*/	unknown,
    /* 174 ???			*/	unknown,
    /* 175 ???			*/	unknown,
    /* 176 ???			*/	unknown,
    /* 177 ???			*/	unknown,
    /* 178 ???			*/	unknown,
    /* 179 ???			*/	unknown,
    /* 180 ???			*/	unknown,
    /* 181 ???			*/	unknown,
    /* 182 ???			*/	unknown,
    /* 183 ???			*/	unknown,
    /* 184 ???			*/	unknown,
    /* 185 ???			*/	unknown,
    /* 186 ???			*/	unknown,
    /* 187 ???			*/	unknown,
    /* 188 ???			*/	unknown,
    /* 189 ???			*/	unknown,
    /* 190 ???			*/	unknown,
    /* 191 ???			*/	unknown,
    /* 192 ???			*/	unknown,
    /* 193 ???			*/	unknown,
    /* 194 ???			*/	unknown,
    /* 195 ???			*/	unknown,
    /* 196 ???			*/	unknown,
    /* 197 ???			*/	unknown,
    /* 198 ???			*/	unknown,
    /* 199 ???			*/	unknown,
    /* 200 ???			*/	unknown,
    /* 201 ???			*/	unknown,
    /* 202 ???			*/	unknown,
    /* 203 ???			*/	unknown,
    /* 204 ???			*/	unknown,
    /* 205 ???			*/	unknown,
    /* 206 ???			*/	unknown,
    /* 207 ???			*/	unknown,
    /* 208 ???			*/	unknown,
    /* 209 ???			*/	unknown,
    /* 210 ???			*/	unknown,
    /* 211 ???			*/	unknown,
    /* 212 ???			*/	unknown,
    /* 213 ???			*/	unknown,
    /* 214 ???			*/	unknown,
    /* 215 ???			*/	unknown,
    /* 216 ???			*/	unknown,
    /* 217 ???			*/	unknown,
    /* 218 ???			*/	unknown,
    /* 219 ???			*/	unknown,
    /* 220 ???			*/	unknown,
    /* 221 ???			*/	unknown,
    /* 222 ???			*/	unknown,
    /* 223 ???			*/	unknown,
    /* 224 ???			*/	unknown,
    /* 225 ???			*/	unknown,
    /* 226 ???			*/	unknown,
    /* 227 ???			*/	unknown,
    /* 228 ???			*/	unknown,
    /* 229 ???			*/	unknown,
    /* 230 ???			*/	unknown,
    /* 231 ???			*/	unknown,
    /* 232 ???			*/	unknown,
    /* 233 ???			*/	unknown,
    /* 234 ???			*/	unknown,
    /* 235 ???			*/	unknown,
    /* 236 EINPROGRESS	*/	"Operation now in progress",
    /* 237 EALREADY		*/	"Operation already in progress",
    /* 238 ENOTSOCK		*/	"Socket operation on non-socket",
    /* 239 EDESTADDRREQ	*/	"Destination address required",
    /* 240 EMSGSIZE		*/	"Message too long",
    /* 241 EPROTOTYPE	*/	"Protocol wrong type for socket",
    /* 242 ENOPROTOOPT	*/	"Protocol not available",
    /* 243 EPROTONOSUPPORT*/	"Protocol not configured or not supported",
    /* 244 ESOCKTNOSUPPORT*/	"Socket type not supported",
    /* 245 ???			*/	unknown,
    /* 246 EPFNOSUPPORT	*/	"Protocol family not supported",
    /* 247 EAFNOSUPPORT	*/	"Address family not supported by protocol family",
    /* 248 EADDRINUSE	*/	"Address already in use",
    /* 249 EADDRNOTAVAIL*/	"Can't assign requested address",
    /* 250 ENETDOWN		*/	"Network is down",
    /* 251 ENETUNREACH	*/	"Network is unreachable",
    /* 252 ENETRESET	*/	"Network dropped connection on reset",
    /* 253 ECONNABORTED	*/	"Software caused connection abort",
    /* 254 ECONNRESET	*/	"Connection reset by peer",
    /* 255 ENOBUFS		*/	"No buffer space available",
    /* 256 EISCONN		*/	"Socket is already connected",
    /* 257 ENOTCONN		*/	"Socket is not connected",
    /* 258 ESHUTDOWN	*/	"Can't send after socket shutdown",
    /* 259 ETOOMANYREFS	*/	"Too many references: can't splice",
    /* 260 ETIMEDOUT	*/	"Connection timed out",
    /* 261 ECONNREFUSED	*/	"Connection refused",
    /* 262 ???			*/	unknown,
    /* 263 ???			*/	unknown,
    /* 264 EHOSTDOWN	*/	"Host is down",
    /* 265 EHOSTUNREACH	*/	"No route to host",
    /* 266 ???			*/	unknown,
    /* 267 ???			*/	unknown,
    /* 268 ???			*/	unknown,
    /* 269 ???			*/	unknown,
    /* 270 ???			*/	unknown,
    /* 271 ???			*/	unknown,
    /* 272 EBADRPC		*/	"RPC struct is bad",
    /* 273 ERPCMISMATCH	*/	"RPC version wrong",
    /* 274 EPROGUNAVAIL	*/	"RPC prog. not avail",
    /* 275 EPROGMISMATCH*/	"Program version wrong",
    /* 276 EPROCUNAVAIL	*/	"Bad procedure for program",
    /* 277 ???			*/	unknown,
    /* 278 ???			*/	unknown,
    /* 279 ???			*/	unknown,
    /* 280 ???			*/	unknown,
    /* 281 ???			*/	unknown,
    /* 282 ???			*/	unknown,
    /* 283 ???			*/	unknown,
    /* 284 ???			*/	unknown,
    /* 285 ???			*/	unknown,
    /* 286 ???			*/	unknown,
    /* 287 ???			*/	unknown,
    /* 288 ???			*/	unknown,
    /* 289 ???			*/	unknown,
    /* 290 ???			*/	unknown,
    /* 291 ???			*/	unknown,
    /* 292 ???			*/	unknown,
    /* 293 ???			*/	unknown,
    /* 294 ???			*/	unknown,
    /* 295 ???			*/	unknown,
    /* 296 ???			*/	unknown,
    /* 297 ???			*/	unknown,
    /* 298 ???			*/	unknown,
    /* 299 ???			*/	unknown,
    /* 300 ENOREMOTE	*/	"Must be done on local machine",
    /* 301 ENONDP		*/	"Need an NDP (8087...) to run",
    /* 302 EBADFSYS		*/	"Corrupted file system detected",
    /* 303 ???			*/	unknown,
    /* 304 ???			*/	unknown,
    /* 305 ???			*/	unknown,
    /* 306 ???			*/	unknown,
    /* 307 ???			*/	unknown,
    /* 308 ???			*/	unknown,
    /* 309 EMORE		*/	"More to do; send message again",
    /* 310 ECTRLTERM	*/	"Remap to controlling terminal",
    /* 311 ENOLIC		*/	"No license",
    /* 312 ESRVRFAULT	*/	"Server fault on msg pass",
	/* 313 EENDIAN		*/	"Endian not supported"
};

const int sys_nerr = sizeof sys_errlist / sizeof sys_errlist[0];
