expr '' '|' ''
expr '' '|' abc
expr '' '|' 0
expr '' '|' -1
expr '' '|' 1
expr '' '|' 5
expr '' '&' ''
expr '' '&' abc
expr '' '&' 0
expr '' '&' -1
expr '' '&' 1
expr '' '&' 5
expr abc '|' ''
expr abc '|' abc
expr abc '|' 0
expr abc '|' -1
expr abc '|' 1
expr abc '|' 5
expr abc '&' ''
expr abc '&' abc
expr abc '&' 0
expr abc '&' -1
expr abc '&' 1
expr abc '&' 5
expr 0 '|' ''
expr 0 '|' abc
expr 0 '|' 0
expr 0 '|' -1
expr 0 '|' 1
expr 0 '|' 5
expr 0 '&' ''
expr 0 '&' abc
expr 0 '&' 0
expr 0 '&' -1
expr 0 '&' 1
expr 0 '&' 5
expr -1 '|' ''
expr -1 '|' abc
expr -1 '|' 0
expr -1 '|' -1
expr -1 '|' 1
expr -1 '|' 5
expr -1 '&' ''
expr -1 '&' abc
expr -1 '&' 0
expr -1 '&' -1
expr -1 '&' 1
expr -1 '&' 5
expr 1 '|' ''
expr 1 '|' abc
expr 1 '|' 0
expr 1 '|' -1
expr 1 '|' 1
expr 1 '|' 5
expr 1 '&' ''
expr 1 '&' abc
expr 1 '&' 0
expr 1 '&' -1
expr 1 '&' 1
expr 1 '&' 5
expr 5 '|' ''
expr 5 '|' abc
expr 5 '|' 0
expr 5 '|' -1
expr 5 '|' 1
expr 5 '|' 5
expr 5 '&' ''
expr 5 '&' abc
expr 5 '&' 0
expr 5 '&' -1
expr 5 '&' 1
expr 5 '&' 5
