expr '' '!=' ''
expr '' '!=' abc
expr '' '!=' 0
expr '' '!=' 2
expr '' '>' ''
expr '' '>' abc
expr '' '>' 0
expr '' '>' 2
expr '' '>=' ''
expr '' '>=' abc
expr '' '>=' 0
expr '' '>=' 2
expr '' '<=' ''
expr '' '<=' abc
expr '' '<=' 0
expr '' '<=' 2
expr abc '!=' ''
expr abc '!=' abc
expr abc '!=' 0
expr abc '!=' 2
expr abc '>' ''
expr abc '>' abc
expr abc '>' 0
expr abc '>' 2
expr abc '>=' ''
expr abc '>=' abc
expr abc '>=' 0
expr abc '>=' 2
expr abc '<=' ''
expr abc '<=' abc
expr abc '<=' 0
expr abc '<=' 2
expr 0 '!=' ''
expr 0 '!=' abc
expr 0 '!=' 0
expr 0 '!=' 2
expr 0 '>' ''
expr 0 '>' abc
expr 0 '>' 0
expr 0 '>' 2
expr 0 '>=' ''
expr 0 '>=' abc
expr 0 '>=' 0
expr 0 '>=' 2
expr 0 '<=' ''
expr 0 '<=' abc
expr 0 '<=' 0
expr 0 '<=' 2
expr 2 '!=' ''
expr 2 '!=' abc
expr 2 '!=' 0
expr 2 '!=' 2
expr 2 '>' ''
expr 2 '>' abc
expr 2 '>' 0
expr 2 '>' 2
expr 2 '>=' ''
expr 2 '>=' abc
expr 2 '>=' 0
expr 2 '>=' 2
expr 2 '<=' ''
expr 2 '<=' abc
expr 2 '<=' 0
expr 2 '<=' 2
