expr a : 'a*'
expr a : '*a*'
expr a : '*a'
expr abc : 'a*'
expr abc : '*a*'
expr abc : '*a'
expr abc : [abc][abc][abc]
expr abc : [a][b][c]
expr abc : [abc][abc][ab]
expr abc : [abc][ac][abc]
expr abc : [bc][abc][abc]
